server:
  port: 8080

spring:
  application:
    name: oauth-client
  security:
    oauth2:
      client:
        registration:
          oauth-client:
            provider: oauth-server
            client-id: oauth-client
            client-secret: 123456789
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/authorized"
            client-name: oauth-client
            scope: openid,profile,read,write
        provider:
          oauth-server:
            issuer-uri: http://localhost:9000

logging:
  level:
    org.springframework.security: INFO